### ISSUE TITLE
Missing "esc_class_labels_indices.csv" file

### ISSUE THREAD

**Issue by kaiw7** [YuanGongND/ast#104]
Hi Yuan, could I know where is the 'esc_class_labels_indices.csv' file? Because I met error about 'FileNotFoundError'. Thank you very much.

**Comment by YuanGongND** [comment]
It is here: https://github.com/YuanGongND/ast/blob/master/egs/esc50/data/esc_class_labels_indices.csv

If you closely follow up the readme file, you should not get this error.

**Comment by kaiw7** [comment]
Hi Yuan, I found that. Thank you very much.
