### ISSUE TITLE
ESC-50-master zip file location has changed

### ISSUE THREAD

**Issue by BehrouzGit** [YuanGongND/ast#122]
Hi team,
Please note that the "esc50_url = 'https://github.com/karoldvl/ESC-50/archive/master.zip'" on the 'pre-esc50.py' should change, based on the changes on the referenced GitHub repo.
Thanks!

**Comment by YuanGongND** [comment]
I do not have a problem to download from this link. Is there a reason to update the link? Thanks!

**Comment by BehrouzGit** [comment]
Thanks for clarification; it was an SSL issue at my end.
