### ISSUE TITLE
AttributeError: module 'numpy.typing' has no attribute 'NDArray'

### ISSUE THREAD

**Issue by nikhilsos** [YuanGongND/ast#135]
Firstly, using cuda 10.1, requirement does not work as it is
Needed to install via:

pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

After that tried running: src/model/ast_models.py
got :
AttributeError: module 'numpy.typing' has no attribute 'NDArray'

**Comment by nikhilsos** [comment]
> Firstly, using cuda 10.1, requirement does not work as it is Needed to install via:
> 
> pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
> 
> After that tried running: src/model/ast_models.py got : AttributeError: module 'numpy.typing' has no attribute 'NDArray'

Update:
worked after relaxing numpy to < 1.23.0 (1.22.4)

**Comment by YuanGongND** [comment]
@nikhilsos thanks so much for sharing and sorry for the version issue. 

numpy to < 1.23.0 (1.22.4) is this a relaxing or constrain? It is a known issue that numpy has a change after this version.

-Yuan

**Comment by nikhilsos** [comment]
@YuanGongND constraining it is, pardon my mistake. I said the exact opposite. I had no idea about that numpy change,  I am relatively new to this.
