### ISSUE TITLE
Use different sample rate 

### ISSUE THREAD

**Issue by hbellafkir** [YuanGongND/ast#24]
Can I use a different sampling rate like 22 kHz for fine tuning?

**Comment by YuanGongND** [comment]
Yes - I think you don't need to change anything of the code for a new sampling rate if you only use ``imagenet_pretrain=True``. 

But our AudioSet pretrained model is trained with 16kHz audios, so it would be better if you resample your audios to 16kHz. The improvement of AudioSet pretraining is obvious for audio event classification tasks. 

-Yuan

**Comment by hbellafkir** [comment]
The problem is, that 16 kHz can only used for frequencies until 8kHz, where my data contains higher frequencies (>8 kHz

**Comment by YuanGongND** [comment]
In that case, you can just use your sample rate and set ``audioset_pretrain=False`` when you initialize the AST model.

-Yuan

**Comment by hbellafkir** [comment]
can I use the audioset weights for my case here?
