### ISSUE TITLE
Inference on CPU ? 

### ISSUE THREAD

**Issue by Enescigdem** [YuanGongND/ast#32]
Hello,
I tried to do inference on cpu.BUT ;
RuntimeError: module must have its parameters and buffers on device cuda:0 error arose. 
What steps should be done ?

**Comment by YuanGongND** [comment]
I think you will need to move both the model and input data to the CPU before the forward pass, e.g., something like ``audio_mode.to('cpu')`` and ``input.to('cpu')``.

-Yuan
