### ISSUE TITLE
No such file or directory: './data/datafiles/esc_train_data_1.json'

### ISSUE THREAD

**Issue by nzhou26** [YuanGongND/ast#4]
Hi Yuan,
I downloaded the model and try to test it with the esc50 data. I tried to run run_esc.sh, but got error for no such file. I download the master.zip, unzip and put it in ./data/ESC-50-master/. I check the run and prep scripts and havn't found any code that makes the directory or download files for ./data/datafiles/ 
Is it a file or data I suppose to download or the file is auomatically generated?

Ningkun

**Comment by YuanGongND** [comment]
Hi Ningkun,

Maybe I forgot to create an empty directory ./data/datafiles/ , but in [here](https://github.com/YuanGongND/ast/blob/481cd0acb38e73bef9ba24b5d0e5d8bf9e5ccf93/egs/esc50/prep_esc50.py#L79) the code does automatically generate json files. 

Could you manually create an empty directory ./data/datafiles/ and re-run prep_esc50.py? Please let me know if this solves the problem. Thanks!

-Yuan

**Comment by nzhou26** [comment]
Hi Yuan,
Thanks for the quick reply.
I manually created the ./data/datafile/ directory and the script is working without no such file error

**Comment by YuanGongND** [comment]
Great to know and thanks for reporting this issue, I have fixed the bug in prep_esc50.py.

-Yuan
