### ISSUE TITLE
training with custom data

### ISSUE THREAD

**Issue by ibrahimrazu** [YuanGongND/ast#40]
Thanks a lot for your amazing work and sharing the code. I had a little question. As I have a video dataset, wanna use it by extracting audios from the videos. Do you recommend any recipe for processing the audio data from the videos? or any raw mp3 would work

Thanks again

**Comment by YuanGongND** [comment]
Hi there, 

To extract audios from videos, I use the [``ffmpeg``](https://stackoverflow.com/questions/9913032/how-can-i-extract-audio-from-video-with-ffmpeg) tool. You can also use other similar tools.

I think mp3 should also work without any change of the code as [``torchaudio.load``](https://pytorch.org/audio/stable/backend.html#torchaudio.backend.sox_io_backend.load) accepts mp3.

But the code was tested on audios of 16kHz sampling rate, so it is better to convert your audio to 16kHz. To check the sampling rate, you can use ``sox --i youraudio.mp3``.

-Yuan

**Comment by ibrahimrazu** [comment]
thanks a lot for your reply. it helps a lot.
