### ISSUE TITLE
results.csv and getting labels per audio file

### ISSUE THREAD

**Issue by Gsantos4** [YuanGongND/ast#42]
Hi Yuan,

Thank you for posting your project and providing ample information about it's elements!

I am running the ESC-50 recipe and I've been struggling to output results. Could you point me towards where the result.csv files get created in the scripts? Moreover, do you know how I could pull out labels, for the sounds files, from the results of that recipe? I am trying to use this recipe for avian call recognition and am struggling with the result gathering.

Thank you, I appreciate any insight you can offer.

**Comment by YuanGongND** [comment]
Hi there,

Result.csv should under the directory you specified in [base_exp_dir](https://github.com/YuanGongND/ast/blob/7252ecec6baf4cc81c7fecd0b6bfabc8e484b685/egs/esc50/run_esc.sh#L35) (click to see the code).

Actually, the recipe automatically saves the predictions of your evaluation set, see [here](https://github.com/YuanGongND/ast/blob/7252ecec6baf4cc81c7fecd0b6bfabc8e484b685/src/traintest.py#L324), it should be under `base_exp_dir/fold{1-5}/predictions/`. 

-Yuan
