### ISSUE TITLE
Question regarding fbank for fine tuning

### ISSUE THREAD

**Issue by krem-cheese** [YuanGongND/ast#52]
Hi Yuan,

Than you for this great work! I am currently fine tuning the models you produced for a project I am working on and really appreciate the opportunity you created for me. I had a question regarding the spectrograms (or fbanks) produced by the wav2vec function.

Currently, I am trying to prepare a dataset to match the requirements of the model but have stumbled upon something that grabs my attention: You have mentioned in the paper that the model acceps variable inputs. Taking a closer look, I have found that this is due to the added padding below the fbank, his is done to fix the input dimensions into the model. However, when I applied this on my own data, I saw that the padding was of different colors depending on the image when I converted them. Here are two examples:
![d4-2 wav](https://user-images.githubusercontent.com/74565702/157323322-94bf8318-7059-49e8-9177-1079d59077c5.jpeg), ![d10-2 wav](https://user-images.githubusercontent.com/74565702/157323332-a812467b-0693-420d-babb-7738396da243.jpeg)
Although I am aware that the values of the solid coloured areas are zeros, I worry that this is indicative of the same colour being attributed to a different value in different spectrograms and how that would imapt the understanding of the model of colour. 

My second question is regarding the use of padding specifically. In the ViT paper as well as AST, images are fed through as a colelction of patches for learning. Any patches that are fully blank naturally would not be adding too much information to the model. However, for the patches that have an overlap of fbank and spectrogram, is there no effect on learning there? Also, if a specific category is relatively shorter in length to another, does the model include that audio file length in its representation of that class?

Any insight on the above would be deeply appreciated.
Thanks again

**Comment by krem-cheese** [comment]
Also, could you comment on the reasoning of the padded regions in the two images above being different colours despite using the same padding and the implications this may have on learning?

Thanks again

**Comment by YuanGongND** [comment]
I think using the mixture of padding and valid spectrogram is fine as padding can be viewed as silence. The different color is due to the matplotlib's colormap setting, if you look at the values of the fbank matrix, they should be same

**Comment by krem-cheese** [comment]
Hi Yuan, thank you for your answers, this can be closed now.
