### ISSUE TITLE
Run ESC-50 fine tuned model on test data with metrics

### ISSUE THREAD

**Issue by p4vlos** [YuanGongND/ast#66]
Hi,
You did great work there! I am planning to use your model for evaluating my data for my research and hopefully publish a paper afterwards! I run the [inference.py](https://github.com/YuanGongND/ast/blob/master/egs/audioset/inference.py) file right now to run on new data, but I am focusing on ESC-50 dataset, which makes sense to use the fine-tuned model.

Is there a script available to use the ESC-50 fine tuned model with the ESC-50 labels in order to get similar results to your paper?

Thank you in advance
Pavlos

**Comment by YuanGongND** [comment]
Hi Pavlos,

Have you checked the [ESC-50 recipe](https://github.com/YuanGongND/ast/tree/master/egs/esc50)? Maybe you can change the code to have (all ESC-50 samples in training) and (your data in the test)? 

-Yuan

**Comment by p4vlos** [comment]
Hi Yuan,

Thank you! That's a good idea. Although I was curious if there's a way to extract the model so I will not have to train it every time.

For now, I can change the ESC-50 recipe as you suggested!

Thank you,
Pavlos

**Comment by YuanGongND** [comment]
Hi Pavlos,

I think the script does save the model checkpoints.

https://github.com/YuanGongND/ast/blob/87a80043154eb4bb34ebceb4dc3e2d91a99235f4/src/traintest.py#L210-L214

Once you finish the training, find the checkpoint and modify `inference.py` (e.g., num of classes, checkpoint path). 

Does that sound reasonable?

-Yuan

**Comment by YuanGongND** [comment]
Btw, the reason why we didn't release the AudioSet + ESC-50 checkpoint was just because ESC-50 is a tiny dataset and reproducing the result is just really one click (we have also the preprocessing code included).

**Comment by p4vlos** [comment]
Thanks a lot! This make sense!
