### ISSUE TITLE
Training ESC50 on constrained GPU resources

### ISSUE THREAD

**Issue by adrianSRoman** [YuanGongND/ast#73]
Hi Yuan, thanks for the amazing research and well documented work.

I am trying to train the ESC50 AST model on a 4GB GPU. Unfortunately, I run out of memory with the default setup from `./run_esc.sh`. I saw previous comments on other issues and I learned that you recommend reducing `batch_size`, `fstride` and `tstride`.  I have applied only the following changes to `run_esc.sh`:
```
batch_size=8 
fstride=16
tstride=16
```
However, when executing the script, I see the following error, which seems to be related to the change to the strides, not to batch_size:
```
---------------AST Model Summary---------------
ImageNet pretraining: True, AudioSet pretraining: True
frequncey stride=16, time stride=16
number of patches=256
Traceback (most recent call last):
  File "/user/i/iran/asroman/ast/egs/esc50/../../src/run.py", line 89, in <module>
    audio_model = models.ASTModel(label_dim=args.n_class, fstride=args.fstride, tstride=args.tstride, input_fdim=128,
  File "/user/i/iran/asroman/ast/src/models/ast_models.py", line 148, in __init__
    new_pos_embed = new_pos_embed.reshape(1, 768, num_patches).transpose(1, 2)
RuntimeError: shape '[1, 768, 256]' is invalid for input of size 294912
```

I would greatly appreciate your help (:

**Comment by YuanGongND** [comment]
Hi there,

Thanks for reporting this. 

I had a quick fix, could you please download the new `src/models/ast_models.py` and replace the old one and get another try? 

Another thing is that with 4GB GPU, the performance could be worse than reported due to the very small `batch_size`. Maybe you could try the max `batch_size` that can be used. Also the learning rate should also be decreased when you decrease the batch size. In the [SSAST](https://github.com/YuanGongND/ssast), we have small and tiny AST model released, which might be a better choice.

-Yuan

**Comment by adrianSRoman** [comment]
Thanks for the prompt response!

I pulled the latest change to `src/models/ast_models.py`. It looks like there is still a dimensions issue:
```
current #epochs=1, #steps=0
Traceback (most recent call last):
  File "/user/i/iran/asroman/ast/egs/esc50/../../src/run.py", line 99, in <module>
    train(audio_model, train_loader, val_loader, args)
  File "/user/i/iran/asroman/ast/src/traintest.py", line 118, in train
    audio_output = audio_model(audio_input)
  File "/user/i/iran/asroman/ast/venvast/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/i/iran/asroman/ast/venvast/lib64/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/user/i/iran/asroman/ast/venvast/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/i/iran/asroman/ast/venvast/lib64/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/user/i/iran/asroman/ast/src/models/ast_models.py", line 179, in forward
    x = x + self.v.pos_embed
RuntimeError: The size of tensor a (602) must match the size of tensor b (258) at non-singleton dimension 1
```
**Note**: I am using the same values as notes in the first comment above.

Thanks! Let me start taking a look at the SSAST repo.

**Comment by YuanGongND** [comment]
That's a bit weird, can you post the entire log?

**Comment by adrianSRoman** [comment]
Here it is:
```
(venvast) ~/asroman/ast/egs/esc50% ./run_esc.sh
+ source ../../venvast/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ unset VIRTUAL_ENV_PROMPT
++ '[' '!' nondestructive = nondestructive ']' 
++ VIRTUAL_ENV=/user/i/iran/asroman/ast/venvast
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/user/i/iran/asroman/ast/venvast/bin:/usr/lib64/qt-3.3/bin:/usr/condabin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/libexe
c/sdcc:/usr/libexec/sdcc
++ PATH=/user/i/iran/asroman/ast/venvast/bin:/user/i/iran/asroman/ast/venvast/bin:/usr/lib64/qt-3.3/bin:/usr/condabin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sb
in:/usr/sbin:/usr/libexec/sdcc:/usr/libexec/sdcc
++ export PATH
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ PS1='(venvast) '
++ export PS1
++ VIRTUAL_ENV_PROMPT='(venvast) '
++ export VIRTUAL_ENV_PROMPT
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
+ export TORCH_HOME=../../pretrained_models
+ TORCH_HOME=../../pretrained_models
+ model=ast
+ dataset=esc50
+ imagenetpretrain=True
+ audiosetpretrain=True
+ bal=none
+ '[' True == True ']'
+ lr=1e-5
+ freqm=24
+ timem=96
+ mixup=0
+ epoch=25
+ batch_size=8
+ fstride=16
+ tstride=16
+ base_exp_dir=./exp/test-esc50-f16-t16-impTrue-aspTrue-b8-lr1e-5
+ python ./prep_esc50.py
{'dog': '0', 'rooster': '1', 'pig': '2', 'cow': '3', 'frog': '4', 'cat': '5', 'hen': '6', 'insects': '7', 'sheep': '8', 'crow': '9', 'rain': '10', 'sea_waves': '11', 'crackl
ing_fire': '12', 'crickets': '13', 'chirping_birds': '14', 'water_drops': '15', 'wind': '16', 'pouring_water': '17', 'toilet_flush': '18', 'thunderstorm': '19', 'crying_baby
': '20', 'sneezing': '21', 'clapping': '22', 'breathing': '23', 'coughing': '24', 'footsteps': '25', 'laughing': '26', 'brushing_teeth': '27', 'snoring': '28', 'drinking_sip
ping': '29', 'door_wood_knock': '30', 'mouse_click': '31', 'keyboard_typing': '32', 'door_wood_creaks': '33', 'can_opening': '34', 'washing_machine': '35', 'vacuum_cleaner':
 '36', 'clock_alarm': '37', 'clock_tick': '38', 'glass_breaking': '39', 'helicopter': '40', 'chainsaw': '41', 'siren': '42', 'car_horn': '43', 'engine': '44', 'train': '45',
 'church_bells': '46', 'airplane': '47', 'fireworks': '48', 'hand_saw': '49'}
fold 1: 1600 training samples, 400 test samples
fold 2: 1600 training samples, 400 test samples
fold 3: 1600 training samples, 400 test samples
fold 4: 1600 training samples, 400 test samples
fold 5: 1600 training samples, 400 test samples
Finished ESC-50 Preparation
+ '[' -d ./exp/test-esc50-f16-t16-impTrue-aspTrue-b8-lr1e-5 ']'
+ mkdir -p ./exp/test-esc50-f16-t16-impTrue-aspTrue-b8-lr1e-5
+ (( fold=1 ))
+ (( fold<=5 ))
+ echo 'now process fold1'
now process fold1
+ exp_dir=./exp/test-esc50-f16-t16-impTrue-aspTrue-b8-lr1e-5/fold1
+ tr_data=./data/datafiles/esc_train_data_1.json
+ te_data=./data/datafiles/esc_eval_data_1.json
+ CUDA_CACHE_DISABLE=1
+ python -W ignore ../../src/run.py --model ast --dataset esc50 --data-train ./data/datafiles/esc_train_data_1.json --data-val ./data/datafiles/esc_eval_data_1.json --exp-di
r ./exp/test-esc50-f16-t16-impTrue-aspTrue-b8-lr1e-5/fold1 --label-csv ./data/esc_class_labels_indices.csv --n_class 50 --lr 1e-5 --n-epochs 25 --batch-size 8 --save_model F
alse --freqm 24 --timem 96 --mixup 0 --bal none --tstride 16 --fstride 16 --imagenet_pretrain True --audioset_pretrain True
I am process 959187, running on cmn37.stanford.edu: starting (Sat Jul  9 15:07:41 2022)
now train a audio spectrogram transformer model
balanced sampler is not used
---------------the train dataloader---------------
now using following mask: 24 freq, 96 time
now using mix-up with rate 0.000000
now process esc50
use dataset mean -6.627 and std 5.358 to normalize the input.
number of classes is 50
---------------the evaluation dataloader---------------
now using following mask: 0 freq, 0 time
now using mix-up with rate 0.000000
now process esc50
use dataset mean -6.627 and std 5.358 to normalize the input.
number of classes is 50
---------------AST Model Summary---------------
ImageNet pretraining: True, AudioSet pretraining: True
frequncey stride=16, time stride=16
number of patches=256

Creating experiment directory: ./exp/test-esc50-f16-t16-impTrue-aspTrue-b8-lr1e-5/fold1
Now starting training for 25 epochs
running on cuda
Total parameter number is : 87.031 million
Total trainable parameter number is : 87.031 million
scheduler for esc-50 is used
now training with esc50, main metrics: acc, loss function: CrossEntropyLoss(), learning rate scheduler: <torch.optim.lr_scheduler.MultiStepLR object at 0x7f46476abc40>
current #steps=0, #epochs=1
start training...
---------------
2022-07-09 15:07:44.856395
current #epochs=1, #steps=0
Traceback (most recent call last):
  File "/user/i/iran/asroman/ast/egs/esc50/../../src/run.py", line 99, in <module>
    train(audio_model, train_loader, val_loader, args)
  File "/user/i/iran/asroman/ast/src/traintest.py", line 118, in train
    audio_output = audio_model(audio_input)
  File "/user/i/iran/asroman/ast/venvast/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/i/iran/asroman/ast/venvast/lib64/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/user/i/iran/asroman/ast/venvast/lib64/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user/i/iran/asroman/ast/venvast/lib64/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/user/i/iran/asroman/ast/src/models/ast_models.py", line 179, in forward
    x = x + self.v.pos_embed
RuntimeError: The size of tensor a (602) must match the size of tensor b (258) at non-singleton dimension 1
+ (( fold++ ))
+ (( fold<=5 ))
+ echo 'now process fold2'
```

**Comment by YuanGongND** [comment]
Sorry for the confusion.

I find the reason. I think setting `audiosetpretrain=False` in `run_esc.sh` could solve the issue. Please also delete the old exp path or change the name of `base_exp_dir` to a new one.

The reason is that - when `audiosetpretrain=True`, it uses our pretrained model trained with setting `fstride=stride=10`, and during the ESC-50 training stage, it assumes the same setting. With `audiosetpretrain=False`, you are free to use any `fstride` and `tstride`. In the meantime, you could choose to use a smaller model at https://github.com/YuanGongND/ast/blob/d7d8b4b8e06cdaeb6c843cdb38794c1c7692234c/src/run.py#L91 with [tiny224, small224, base224, base384]. 

However, specifically for the ESC-50 dataset, audioset pretraining helps a lot (~10%). So another workaround is to keep `fstride=stride=10` and `audiosetpretrain=True` but tune the `batch_size` to a smaller value (and also decrease the learning rate accordingly). 

With a 4GB GPU, I don't know which solution would be better. Other options could be Google Colab with a paid plan. I might plan to build one at a later time, but not immediately.

Best,
Yuan

**Comment by adrianSRoman** [comment]
Hi Yuan, 

Thanks for your help, that makes a lot of sense, I have set `audiosetpretrain=False` and the model seems to be training now (:

By the way, given my constrained GPU, do you still recommend me using the AST model or would I be better off using the SSAST model? All I need is to play around with the ESC50 dataset, have SOTA (or close) results for inference, and have the tools to potentially bring in other dataset to train sound event classification models using the PSLA pipeline.

Best, 
Adrian S Roman

**Comment by YuanGongND** [comment]
> By the way, given my constrained GPU, do you still recommend me using the AST model or would I be better off using the SSAST model? All I need is to play around with the ESC50 dataset, have SOTA (or close) results for inference, and have the tools to potentially bring in other dataset to train sound event classification models using the PSLA pipeline.

That's what I am unsure about. SSAST pretraining (ssast repo) and AudioSet pretraining (this repo) are similar, both are much better than no pretraining (i.e., the setting you are currently using). SSAST repo provides tiny and small pretrained models while this repo only provides the base model, but SSAST repo also needs some change to work for tiny/small pretrained model (e.g., learning rate, batch size, etc). 

Maybe you could try comparing the two options - 1) the one your are using, i.e., setting `audiosetpretrain=False`, `fstride=tstride=16` with a larger `batch_size`. 2) setting `audiosetpretrain=True`, `fstride=tstride=16` with the largest`batch_size` you could use, note to change learning rate accordingly to the batch size, e.g., if you use a 10X smaller batch size, also use a 10X smaller learning rate. In my opinion, the first option has no chance to get close to the SOTA as audioset pretraining is crucial. The second option, if you could have a reasonable batch size, and search around the optimal learning rate, is possible to somehow close to the SOTA. That's just my guess.

**Comment by adrianSRoman** [comment]
Awesome! Thanks for resolving my questions and guiding me on the things I will need. 

Best, 
Adrian S Roman
