### ISSUE TITLE
Sorry, I have a stupid question about how to download audioset

### ISSUE THREAD

**Issue by liyunlongaaa** [YuanGongND/ast#82]
I only downloaded the tfrecord file on the audioset official website, and there is no audio file, or do I need to pay to download it?

**Comment by YuanGongND** [comment]
Hi there, due to copyright issues, the dataset collectors didn't release the raw audio/video, you will need to use some tool like youtube-dl to download data, which is a non-trivial process.

-Yuan

**Comment by liyunlongaaa** [comment]
Thank you!

**Comment by liyunlongaaa** [comment]
Is there a way to use tf-record to do this experiment, because the official website says "Frame-level features are stored as tensorflow.SequenceExample protocol buffers.", can this avoid downloading the original audio file?

**Comment by thelou1s** [comment]
@liyunlongaaa I have the whole audioset files in netdisk, do you still need now? (About 100GB, I don't remember)

**Comment by liyunlongaaa** [comment]
> @liyunlongaaa I have the whole audioset files in netdisk, do you still need now? (About 100GB, I don't remember)

oh, Thank you very much for your help, but I don't need it anymore. Thank you very much.

**Comment by ASMIftekhar** [comment]
Hello @thelou1s,
Sorry for commenting out old. Is there a direct link to download the full dataset?

**Comment by thelou1s** [comment]
@ASMIftekhar 
link: https://pan.baidu.com/s/1mD52damicvRCl5r9hbIRZA?pwd=m1jt 
password: m1jt
