### ISSUE TITLE
Q: Audio-MAE reports that AST's performance on VoxCeleb1 is 41.1%, but not listed on the AST paper

### ISSUE THREAD

**Issue by daisukelab** [YuanGongND/ast#86]
Hi @YuanGongND,

Thanks for your work.
I'm wondering if there is any AST result on the VoxCeleb1 because the [Audio-MAE paper](https://arxiv.org/abs/2207.06405) shows that the AST result is 41.1%.
Is this official result published before?

I would appreciate it if I could confirm.
Thanks in advance.
P.S. I found your new paper CAV-MAE (https://arxiv.org/abs/2210.07839) very interesting. Thank you for the paper too.

**Comment by YuanGongND** [comment]
Hi Daisuke, 

It's great to hear from you. I have read multiple of your papers, they are always inspiring. And thanks for your kind words!

Regarding your question, I am not involved in the Audio-MAE paper, but I think they are referring to Table 1 of [SSAST Paper](https://ojs.aaai.org/index.php/AAAI/article/download/21315/21064), second row "AST-IM + KD", where we report the result for an AST model with ImageNet supervised pretraining but _without_ any AudioSet pretraining, which matches "AST-S" in Table 7 of the AST model. More specifically, we do end-to-end finetuning with the SUPERB code with settings at https://github.com/YuanGongND/ssast/tree/main/src/finetune/superb/voxceleb. Please note we were using an old version of SUPERB. 

Hope this helps.

Best,
Yuan

**Comment by daisukelab** [comment]
Hi Yuan,

Thank you for your quick response and kind words too!

And thank you for taking the time to confirm the results.
I understood that they would be referring to the results in Table 1 of the SSAST paper without AudioSet pretraining.
This would explain the large performance gap reported in the Audio-MAE paper.

I really appreciate your sparing time for us to make things clear.
Thank you very much!
